### ISSUE TITLE
ImportError: cannot import name 'Ego_Centric_HOI_Detector' from 'handmocap.hand_bbox_detector'

### ISSUE THREAD

**Issue by Mq-Zhang1** [NVlabs/affordance_diffusion#13]
Thank you for showing such a fantastic work! I am interested in the hand contact evaluation shown in inference, However, when running the code, an error :cannot import name 'Ego_Centric_HOI_Detector' from 'handmocap.hand_bbox_detector' appears

Is it possible to give some hint on how to fix this problem or some details about how to evaluate the contact recall? Thank you so much for your time!

**Comment by JudyYe** [comment]
Hi, thank you for your interests. We've written a wrapper for Ego_Centric_HOI_Detector to additionally return the classification score for the bounding box. However, I admit that I did not publish the most up-to-date code. I will fix it ASAP. But unfortunately, I don't have bandwidth to fix it by this week. I apologize for it.
