### ISSUE TITLE
Is config.yaml missed?

### ISSUE THREAD

**Issue by ccmCCMfk** [NVlabs/affordance_diffusion#6]
After python inference.py data.data_dir='docs/demo/*.*g' test_num=3,FileNotFoundError: [Errno 2] No such file or directory: '/data/PycharmProjects/affordance_diffusion/output/release/layout/config.yaml',do you know how to solve this problem?and the same error occured when python -m scripts.interpolate dir=docs/demo_inter,looking forward to your reply,thanks.

**Comment by dqj5182** [comment]
Same problem

**Comment by dqj5182** [comment]
@ccmCCMfk Did you solve the issue?
